In [1]:
#NUMPY ASSIGNMENT.
import numpy as np
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
l = [0,1,2,3,4,5]

arr = np.array(l)

In [2]:
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.dtype

dtype('int32')

In [5]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [6]:
#yes,its datatype is float64

In [7]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr1 = np.array([5+6j,7+2j,8+3j])

In [8]:
arr1

array([5.+6.j, 7.+2.j, 8.+3.j])

In [9]:
arr1.dtype

dtype('complex128')

In [10]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type.
array =np.array( [1,2,3,4,5,6])
array.dtype

dtype('int32')

In [11]:
array = np.array(array,dtype = 'float32')
array

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [12]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
k = np.linspace(0,5)

In [13]:
k.dtype

dtype('float64')

In [14]:

k = np.array(k,dtype = 'float32')

In [15]:
k

array([0.        , 0.10204082, 0.20408164, 0.30612245, 0.40816328,
       0.5102041 , 0.6122449 , 0.71428573, 0.81632656, 0.9183673 ,
       1.0204082 , 1.1224489 , 1.2244898 , 1.3265306 , 1.4285715 ,
       1.5306122 , 1.6326531 , 1.7346939 , 1.8367347 , 1.9387755 ,
       2.0408163 , 2.142857  , 2.2448978 , 2.3469388 , 2.4489796 ,
       2.5510204 , 2.6530612 , 2.7551022 , 2.857143  , 2.9591837 ,
       3.0612245 , 3.1632652 , 3.2653062 , 3.367347  , 3.4693878 ,
       3.5714285 , 3.6734693 , 3.7755103 , 3.877551  , 3.9795918 ,
       4.0816326 , 4.1836734 , 4.285714  , 4.387755  , 4.4897957 ,
       4.591837  , 4.6938777 , 4.7959185 , 4.897959  , 5.        ],
      dtype=float32)

In [16]:
k.dtype

dtype('float32')

In [17]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
type
def array_attributes(arr):
    return arr.shape,arr.size,arr.dtype
arr = np.array([[1,2,3,4,5,6]])
array_attributes(arr)

((1, 6), 6, dtype('int32'))

In [18]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim
arr = np.array([1,2,3,4,5,6,7,8])
array_dimension(arr)

1

In [19]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
def item_size_info(arr):
    return arr.itemsize,arr.nbytes
arr = np.array([1,2,3,4,5,6,7,8])
item_size_info(arr)

(4, 32)

In [20]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
array_strides(arr)

(12, 4)

In [21]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array
def shape_stride_relationship(arr):
    return arr.strides,arr.shape
print("array strides:",arr.strides)
print("array shape :",arr.shape)
arr = np.array([[1,2,3,4,5]])
shape_stride_relationship(arr)

array strides: (12, 4)
array shape : (3, 3)


((20, 4), (1, 5))

In [22]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
#zeros with `n` elements.
def create_zeros_array(n):
    arr = np.zeros(n)
    return arr
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [23]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
#NumPy array filled with ones of size `rows x cols`
def create_ones_matrix(rows,cols):
    arr=np.ones((rows,cols))
    return arr
create_ones_matrix(8,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`

In [25]:
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
generate_range_array(0,20,3)
    

array([ 0,  3,  6,  9, 12, 15, 18])

In [26]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)
generate_linear_space(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [27]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
#identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)
create_identity_matrix(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(list):
    return np.array(list)
list_to_array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr = np.array([1,2,3,4,5])
varr = arr.view()
print(arr)
varr[0]=10
print(varr)
#both shares the same data but sre different objects.

[1 2 3 4 5]
[10  2  3  4  5]


In [30]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def array_concatenate(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis)
arr1 = [[1,2,3,4,5]]
arr2=[[6,7,8,9,4]]
axis = 0
array_concatenate(arr1,arr2,axis)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 4]])

In [31]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`

In [32]:
a = np.array([[1,2,3],[6,7,8]])
b = np.array(([4,5],[9,10]))

In [33]:
np.concatenate((a,b),axis = 1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertically_stack_arrays(arraylist):  
    return   np.vstack(arraylist)
arr1=np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[9,8,7],[4,3,5]])
arr3 = np.array([[10,11,12],[13,14,15]])
arraylist = [arr1,arr2,arr3]
print(np.vstack(arraylist))

[[ 1  2  3]
 [ 4  5  6]
 [ 9  8  7]
 [ 4  3  5]
 [10 11 12]
 [13 14 15]]


In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
#with a given step size.
def array(start,end,step):
    return np.arange(start,end,step)
res = array(1,10,2)
print(res)

In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)
def array(start,end,step):
    return np.linspace(start,end,step)
res = array(0,1,10)
print(res)

In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)

In [ ]:
def array(start,end,step):
    return np.logspace(np.log10(start),np.log10(end),step)
res = array(1,1000,5)
print(res)

In [ ]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
#are random integers between 1 and 100.
import pandas as pd

In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [ ]:
array.shape

In [ ]:
df = pd.DataFrame(array)

In [ ]:
df

In [ ]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
#with zeros. Use NumPy operations within the Pandas DataFrame.
def pandafunc(df,col):
    if col in df.columns:
        df[col] = np.where(df[col]<0,0,df[col])
    else:
        print("please pass valid arguments")

In [ ]:
data = {'A': [1, -2, 3, -4, 5], 'B': [-1, 2, -3, 4, -5]}
df = pd.DataFrame(data)

In [ ]:
pandafunc(df,'A')

In [ ]:
df

In [ ]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]#indexing start from zero third element is 30

In [ ]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1][2] #or we can use arr_2d[1,2]

In [ ]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
arr1=[]
for i in arr:
    if i > 5:
        arr1.append(i)

In [ ]:
arr1

In [ ]:
#method 2:
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
grater_than_5 = arr[mask]
grater_than_5

In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]#elements from the index 2 to 5

In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]

In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
#provided in another array.
def elements(arr,indices):
    return np.take(arr,indices)
arr = [[1,2,3],[4,5,6],[7,8,9]]
indices = np.array([[0, 2], [1, 1], [2, 0],[8,7]])
elements(arr,indices)

In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
#boolean indexing

In [ ]:
arr = np.array([4,5,3,200,86,55,73])
def returnelements(arr,threshold):
    mask = arr>threshold
    return arr[mask]
returnelements(arr,70)

In [ ]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
#separate arrays for each dimension.
def elements3d(arr,indices_0,indices_1,indices_2):
    return arr[indices_0,indices_1,indices_2]
arr = np.arange(27).reshape((3,3,3))
indices_0 = np.array([0, 1,2])
indices_1 = np.array([2, 0,1])
indices_2 = np.array([0, 2,0])
elements3d(arr,indices_0,indices_1,indices_2)

In [35]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
#using boolean indexing.
arr = np.array([4,5,3,200,86,55,73])
def returnelements2(arr,one,two):
    mask = (arr>two)&(arr<one)
    return arr[mask]
returnelements2(arr,70,50)

array([55])

In [36]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
#in separate arrays
def elementsrc(arr,row,col):
    return arr[row,col]
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row = np.array([0, 2])
col = np.array([0, 2])
elementsrc(arr,row,col)

array([1, 9])

In [37]:
#6. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [39]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
#corresponding element in arr1 using NumPy broadcasting.
arr1 = np.arange(3).reshape(1,3)
arr2 = np.arange(12).reshape(3,4)

In [40]:
arr1.shape

(1, 3)

In [41]:
arr2.shape

(3, 4)

In [42]:
aT = arr1.T

In [43]:
aT * arr2

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [44]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
#NumPy broadcasting.

In [45]:
arr1 =np.array([1,2,3,4]).reshape(1,4)

In [46]:
arr1.shape

(1, 4)

In [47]:
arr2 = np.arange(12).reshape(4,3)

In [48]:
arr2.shape

(4, 3)

In [49]:
aT = arr1.T
arr2 + aT

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [50]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
#broadcasting.
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).reshape(1,3)

In [51]:
arr1

array([[0],
       [1],
       [2]])

In [52]:
arr2

array([[0, 1, 2]])

In [53]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [54]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
#broadcasting. Handle the shape incompatibility.
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(4).reshape(2,2)

In [55]:
arr1 = arr1.T

In [56]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [57]:
#41. Calculate column wise mean for the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr,axis = 0)
mean

array([2.5, 3.5, 4.5])

In [58]:
# Find maximum value in each row of the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_value = arr.max(axis = 1)
max_value

array([3, 6])

In [59]:
#method2
max_value = np.max(arr,axis = 1)
max_value

array([3, 6])

In [60]:
#43. For the given array, find indices of maximum value in each column
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_max_index = np.argmax(arr,axis = 1)
col_max_index

array([2, 2], dtype=int64)

In [61]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.sum(axis = 1)

array([ 6, 15])

In [62]:

def moving_sum(arr, window_size=2):
    return np.array([np.sum(arr[i:i+window_size]) for i in range(len(arr) - window_size + 1)])
result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Moving sum along rows:")
print(result)

Moving sum along rows:
[[ 3  5]
 [ 9 11]]


In [63]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
even = np.all(arr%2 == 0,axis = 0)
even

array([False, False, False])

In [64]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
#reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
def reshape(arr,m,n):
    return arr.reshape(m,n)
m,n = 6,1
reshape(original_array,m,n)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
#47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    return [element for row in matrix for element in row]
flatten_matrix(input_matrix)

[1, 2, 3, 4, 5, 6]

In [66]:
#48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concat = np.concatenate((array1,array2),axis = 0)
concat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1 = np.split(original_array,3,axis = 0)
a2 = np.split(original_array,3,axis = 1)
print("along rows",a1)
print("along column",a2)

along rows [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
along column [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [68]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
def insert_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete):
    insert = np.insert(original_array,indices_to_insert,values_to_insert)
    print(insert)
    delete = np.delete(original_array,indices_to_delete)
    print(delete)
    print(original_array)
insert_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete)

[ 1  2 10  3  4 11  5]
[1 3 5]
[1 2 3 4 5]


In [69]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
#Perform element-wise addition between `arr1` and `arr2`arr1 = np.random.randint(1,11,10)
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)
result = np.add(arr1,arr2)
result

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
#from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
result = np.subtract(arr1,arr2)
result

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [71]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
#Perform element-wise multiplication between `arr1` and `arr2`
arr1 = np.arange(1,6)
arr2 = np.random.randint(1,10,size = 5)
result = np.multiply(arr1,arr2)
result

array([ 8,  8, 18,  8, 30])

In [72]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
#to 5. Perform element-wise division of `arr1` by `arr2`
arr2 = np.random.randint(1,6,5)
arr1 = np.arange(2,12,2)
result = arr1/arr2
print(arr1)
print(arr2)
result

[ 2  4  6  8 10]
[3 1 5 3 2]


array([0.66666667, 4.        , 1.2       , 2.66666667, 5.        ])

In [73]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.random.randint(1,6,5)
print(arr1)
arr2 = arr1[::-1]
print(arr2)
result = np.power(arr1,arr2)
result

[3 3 3 3 4]
[4 3 3 3 3]


array([81, 27, 27, 27, 64])

In [74]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring(array, substring):
    count = sum(substring in string for string in array)
    return count
substring = 'hello'
count_substring(arr, substring)

3

In [75]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [76]:
def uppercase(arr):
    uppercase_characters = [char for string in arr for char in string if char.isupper()]
    return "".join(uppercase_characters)
k = uppercase(arr)
k

'HWOAIGPT'

In [77]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
k = np.char.replace(arr,'apple','mango')
k

array(['mango', 'banana', 'grape', 'pinemango'], dtype='<U9')

In [78]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [79]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
lengths = np.vectorize(len)(arr)
max_len = np.max(lengths)
max_len

9

In [80]:
a = np.linspace(1,1000,100)
mean = np.mean(a)
median = np.median(a)
std = np.std(a)
var = np.var(a)
print(mean,median,std,var)

500.5 500.5 291.2848886633777 84846.88636363637


In [81]:
a = np.linspace(1,100,50)
q25 = np.percentile(a,[25])
q75 = np.percentile(a,[75])
print(q25,q75)

[25.75] [75.25]


In [82]:
a = np.array([2,6,33,45,45,67,33,45])
b = np.array([4,6,2,34,56,78,95,54])
corr_coef = np.corrcoef(a,b)[0,1]
corr_coef

0.6705903078599633

In [83]:
a = np.matrix([[3,3],[4,5]])
b = np.matrix([[4,5],[6,4]])
dot_product = np.dot(a,b)
dot_product

matrix([[30, 27],
        [46, 40]])

In [84]:
a = np.linspace(10,1000,50)
p1 = np.percentile(a,[10,50,90])
q1 = np.quantile(a,[0.25,0.75])
print(p1[0],p1[1],p1[2])
print(q1[0],q1[1])

109.0 505.0 901.0
257.5 752.5


In [85]:
a = np.array([5,8,9,7,4])
k = np.where(a==8)#to find the index of 8.
k

(array([1], dtype=int64),)

In [86]:
a = np.random.randn(10)
a.sort()
a

array([-1.44500568, -0.91041837, -0.58621209, -0.13878083, -0.12747841,
       -0.03681268,  0.82472799,  1.15333501,  1.22042739,  1.45157881])

In [87]:
arr = np.array([12, 25, 6, 42, 8, 30])
k = arr[arr>20]
k

array([25, 42, 30])

In [88]:
arr = np.array([1, 5, 8, 12, 15])
k = arr[arr%3==0]
k

array([12, 15])

In [89]:
arr = np.array([10, 20, 30, 40, 50])
k = (arr<=40)&(arr>=20)
print(arr[k])

[20 30 40]


In [90]:
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [91]:
arr = np.array([1, 2, 3], dtype=np.int32)

In [92]:
arr.byteswap(True)

array([16777216, 33554432, 50331648])

In [93]:
arr = np.array([1, 2, 3], dtype=np.int32)
k = arr.newbyteorder()
print(k)

[16777216 33554432 50331648]


In [94]:
arr = np.array([1, 2, 3], dtype=np.int32)
k = arr.newbyteorder('S')
k

array([16777216, 33554432, 50331648], dtype='>i4')

In [95]:
arr = np.array([1, 2, 3],dtype = np.int32)
k = arr.dtype.byteorder
if k == "=":
    print("no byte swapping is needed")
if k=="<":
    print("byte swapping is neessary for big endian systems")
if k ==">":
    print("byte swapping is necessary for little endian systems")

no byte swapping is needed


In [96]:
arr1 = np.array([5,6,9,7,4,8,2,3,1])
copy_arr = arr1.copy()
copy_arr[1]=50
print(arr1)
print(copy_arr)#it doesnt effects.

[5 6 9 7 4 8 2 3 1]
[ 5 50  9  7  4  8  2  3  1]


In [100]:
arr = np.random.randint(0,10,size = (3,3))
print(arr)
view_slice = arr[:2,:2]
print(view_slice)
view_slice[0,0] = 5
print(arr)#the change affected the original matrix.

[[6 9 3]
 [6 7 7]
 [8 1 1]]
[[6 9]
 [6 7]]
[[5 9 3]
 [6 7 7]
 [8 1 1]]


In [109]:
arr = np.arange(1,13).reshape(4,3)
print(arr)
view_b = arr[:2,:2]
print(view_b)
view_b=view_b+5
print(view_b)
print(arr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2]
 [4 5]]
[[ 6  7]
 [ 9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
orig_arr = np.arange(1,9).reshape(2,4)
print(orig_arr)
reshaped_view = orig_arr.reshape(4,2)
reshaped_view[0,0]=5
print(orig_arr)#yes it reflects the changes.

[[1 2 3 4]
 [5 6 7 8]]
[[5 2 3 4]
 [5 6 7 8]]


In [125]:
arr = np.random.randint(0,11,size = (3,4))
print(arr)
data_copy =  arr[arr>5]
print(data_copy)
data_copy[0] = 4
print(data_copy)
print(arr)#no it deoesnt reflect any change

[[ 6  1  5  9]
 [ 6  7  9  7]
 [ 0  7 10  0]]
[ 6  9  6  7  9  7  7 10]
[ 4  9  6  7  9  7  7 10]
[[ 6  1  5  9]
 [ 6  7  9  7]
 [ 0  7 10  0]]


In [130]:
m1 = np.matrix([1,5,8,9,6,3,8,7]).reshape(2,4)
m2 = np.matrix([8,9,7,1,2,6,0,9]).reshape(2,4)
print(m1-m2)
print(m1+m2)

[[-7 -4  1  8]
 [ 4 -3  8 -2]]
[[ 9 14 15 10]
 [ 8  9  8 16]]


In [133]:
m1 = np.matrix([5,8,9,6,3,4]).reshape(3,2)
print(m1)
m2 = np.matrix([2,8,7,4,6,1,8,7]).reshape(2,4)
print(m2)
mul = np.matmul(m1,m2)
print(mul)

[[5 8]
 [9 6]
 [3 4]]
[[2 8 7 4]
 [6 1 8 7]]
[[ 58  48  99  76]
 [ 54  78 111  78]
 [ 30  28  53  40]]


In [135]:
E = np.matrix([5,8,7,9,4,6]).reshape(2,3)
print(E)
E_t = E.T#E transpose.
print(E_t)

[[5 8 7]
 [9 4 6]]
[[5 9]
 [8 4]
 [7 6]]


In [142]:
F = np.matrix([5,8,7,9,4,6,10,17,0]).reshape(3,3)
print(F)
det = np.linalg.det(F)
print(det)#it's determinant.

[[ 5  8  7]
 [ 9  4  6]
 [10 17  0]]
761.0000000000002


In [146]:
G =  np.matrix([5,8,7,9,4,6,10,17,0]).reshape(3,3)
print(G)
inv = np.linalg.inv(G)
print(inv)

[[ 5  8  7]
 [ 9  4  6]
 [10 17  0]]
[[-0.13403417  0.15637319  0.02628121]
 [ 0.07884363 -0.09198423  0.04336399]
 [ 0.14848883 -0.0065703  -0.06833114]]
